package com.example.atractivossv;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

import androidx.annotation.Nullable;

public class AdminSQLiteOpenHelper extends SQLiteOpenHelper
{
    //Implementacion de metodos de la clase
    public AdminSQLiteOpenHelper(@Nullable Context context, @Nullable String name, @Nullable SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }
    //Implementacion de metodos de la clase(Creacion de la base de datos)
    @Override
    public void onCreate(SQLiteDatabase BaseDeDatos) {

        //CREACION DE TABLAS NECESARIAS
        BaseDeDatos.execSQL("create table usuario(cod integer primary key autoincrement," +
                " nombre text," +
                " apellido text," +
                " correo text," +
                " contrasenia text);");

        BaseDeDatos.execSQL("create table sitios_arqueologicos(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table balnearios(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table catedrales(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table lagos(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table miradores(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table montanias(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table playas(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table rutas(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table volcanes(" +
                " cod integer primary key autoincrement," +
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        BaseDeDatos.execSQL("create table recomendaciones_lugar(" +
                " cod integer primary key autoincrement," +
                " tipoLugar text,"+
                " nombre text," +
                " municipio text," +
                " departamento text," +
                " descripcion text);");

        //Implementacion del metodo de insercion
        insertDatos(BaseDeDatos);
    }

    //Implementacion de metodos de la clase
    @Override
    public void onUpgrade(SQLiteDatabase sqLiteDatabase, int i, int i1) {
    }

    //Creacion del metodo encargado de insertar los datos a cada una de la tablas
    public void insertDatos(SQLiteDatabase BaseDeDatos)
    {
        //INSERCION DE PLAYAS
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Costa del Sol',                  'San Luis La Herradura',    'La Paz',       'Conocida como \"Paraíso entre dos aguas\", Costa del Sol es una península de 15 kilómetros de arenas grises, rodeada por las aguas del océano Pacífico y el Estero de Jaltepeque. \nEs una de las playas más turísticas de El Salvador, encontrándose en sus entornos los complejos hoteleros más exclusivos del país. Además de playa, este destino permite descubrir las maravillas naturales del Estero de Jaltepeque, un estuario de pequeñas islas y manglares, donde habita una extraordinaria biodiversidad de aves migratorias. Otra maravilla del paisaje, lo configuran los bancos de arena del estuario, acumulaciones de grava y arena, que se pueden apreciar al bajar la marea.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Barra de Santiago',              'Jujutla',                  'Ahuachapan',   'Considerada una de las mejores playas de El Salvador en la Barra de Santiago se encuentra un importante humedal rodeado de manglares, ubicado dentro de los municipios de Jujutla y San Francisco Menéndez, para amantes de la naturaleza, se encuentra situada en uno de los bosques de manglares más grandes del país, lugar que da refugio a una invaluable vida silvestre, siendo posible avistar caimanes, cocodrilos y tortugas marinas. A lo largo de sus arenas se extienden numerosos restaurantes donde disfrutar de los productos del mar, mientras que sus aguas más bien calmas, son ideales para la práctica de deportes acuáticos, como el kayak, el velerismo y el esquí acuático.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Las Flores',                     'Chirilagua',               'San Miguel',   'Se encuentra situada en la zona conocida como el oriente salvaje, en un escenario de grandes formaciones rocosas y bosques de manglares. Cuenta con arenas grises y grandes olas, siendo reconocida como una de las mejores playas de El Salvador para practicar surf, que se extienden una tras otra por varios kilómetros, desde el oriente de la costa salvadoreña hacia el occidente.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('El Tunco',                       'Tamanique',                'La Libertad',  'Una curiosa roca en forma de cerdo (conocida localmente como \"Tunco\") es la que le da el nombre a esta famosa playa. De arenas negras y grandes olas, es otra de las mejores playas de El Salvador para la práctica de surf, acogiendo cada año importantes campeonatos relacionados a este deporte. El Tunco es también famosa por su animada atmósfera, siendo uno de los sitios preferidos de mochileros y turistas jóvenes. Es emplazamiento de un gran número de bares y fiestas playeras con música en vivo y fogatas, además de una amplia oferta de hospedaje de bajo costo.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('El Sunzal',                      'Tamanique',                'La Libertad',  'En un entorno de acantilados y cocoteras, se encuentra situada playa El Sunzal, una hermosa playa de arenas oscuras y grandes olas, reconocida internacionalmente como uno de los mejores rincones del planeta para la práctica de surf. Además de surf, esta playa cuenta con hermosos entornos para pasear y zonas de agua calma para practicar snorkeling y buceo de baja profundidad. Frente a la playa, se puede disfrutar de algún platillo típico, en alguno de los tantos restaurantes alineados frente al mar.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('El Zonte',                       'Chiltiupan',               'La Libertad',  'Otra de las famosas playas de El Salvador situadas en el departamento de La Libertad, compartiendo la calidad de olas de El Tunco y El Sunzal para la práctica de surf, además de sus espectaculares escenarios de cocoteras, acantilados y arenas oscuras. El Zonte también es uno sitio ideal para aprender a practicar surf, contando con varias escuelas y profesores capacitados para enseñar este deporte. El animado ambiente bohemio de la zona termina por complementar sus atractivos, congregando una amplia oferta de hospedaje, restaurantes y bares.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Mizata',                         'Santa Maria Mizata',       'Sonsonate',    'La playa de Mizata se encuentra situada en el departamento de Sonsonate, en un pequeño pueblo donde todo gira en torno al surf, en un ambiente mucho más tranquilo y menos concurrido que el de las turísticas playas del departamento de la Libertad. Mizata es considerada el último spot de surf de calidad hacia al oeste del país. Esta playa de arenas oscuras se extiende por aproximadamente 1 kilómetro, encontrándose dividida en dos por la boca del río Mizata. Los entornos de la playa, con bosques tropicales y acantilados, impregnan la zona de una especial belleza.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Los Cóbanos',                    'Acajutla',                 'Sonsonate',    'Considerada una de las mejores playas de El Salvador para la práctica de buceo y snorkeling, contando con varios arrecifes rocosos, que hacen de habitat a una amplia biodiversidad marina. Los mejores meses para la práctica de este deporte son los meses de octubre a febrero. Los Cóbanos, también están entre las playas más bellas del país, con kilómetros de arenas doradas de suave pendiente, en entornos de bosques de cocoteras. Sumado a su belleza escénica, Los Cóbanos, cuentan con el atractivo de su vasta oferta de turismo, con una amplia variedad de hoteles para distintos presupuestos, restaurantes y campos de golf.')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Península de San Juan del Gozo', 'San Dionisio',             'Usulutan',     'Península emplazada en la Bahía de Jiquilisco, un sitio declarado como \"Humedal de Importancia Internacional\" (Ramsar), congregando bosques de manglares y numerosos esteros, que dan hogar a una inmensa biodiversidad marina y terrestre. La zona más famosa de la península se encuentra en la Punta de San Juan, un área de playas de arenas doradas y aguas calmas, con los escenarios montañosos de la cordillera volcánica Tecapa-Chinameca como telón de fondo. Si se es afortunado también se pueden apreciar tortugas marinas anidando en las arenas de las playas')");
        BaseDeDatos.execSQL("INSERT INTO playas (nombre,municipio,departamento,descripcion)VALUES('Golfo de Fonseca',               'Conchagua',                'La Union',     'Conjunto de islas volcánicas compartidas con Honduras y Nicaragua, reconocidas por su inmensa biodiversidad de flora y fauna, albergando impresionantes escenarios de manglares y playas vírgenes. Sus islas más famosas corresponden a Conchaguita, Zacatillo, Meanguera del Golfo y Martín Pérez, cada una con playas hermosas poco explotadas turísticamente, lo que permite un contacto único con la naturaleza. Pequeñas aldeas de pescadores y las laderas verdes del Volcán Conchagua, complementan sus paisajes')");

        //INSERCION DE BALNEARIOS
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Termos del río parque acuático',   'Zapotitan',            'La Libertad',  'Es un parque acuático (turicentro) ubicado en carretera hacia Santa Ana. Es el primer parque turístico de aguas termales en El Salvador. Es un complejo recreativo de 14 manzanas, donde podrá disfrutar de canchas deportivas, amplios jardines, amplias áreas para descansar y paseos a caballo, todo lo anterior agregado a su principal atracción: Las aguas termales.')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Parque acuático Agape',            'Sonzacate',            'Sonsonate',    'En el \"Parque Acuático Agape\" se puede disfrutar de amplias instalaciones, toboganes acuáticos, piscinas para niños y adultos, zonas verdes y área de recreación infantil. Ubicado en dirección: Km.63 Carretera de San Salvador a Sonsonate, Sonzacate, Sonsonate')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Ichanmichen, Parque acuatico',     'Zacatecoluca',         'La Paz',       'Su nombre en náhuatl significa: \"Morada de los Pececitos\" o \"La Cueva de los Pececitos\", está ubicado a 52 kilómetros de la ciudad de San Salvador. El lugar tiene un área de 43 manzanas de terreno y posee las etapas de piscina \"Zona popular\", \"Zona familiar\" y \"Zona la fuente\", con dos piscinas para niños y cinco estanques; así como dos canales de nacimiento de agua, un tobogán de 6.50 metros de altura y dos toboganes de caída libre.')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('La Toma de Quezaltepeque',         'Quezaltepeque',        'La Libertad',  'Quetzales, \"Ciudad Preciosa\" o \"Lugar hermoso\". La Toma de Quezaltepeque es un parque acuático que se ubica al Noroeste de la ciudad de Quezaltepeque en el departamento de la Libertad, ubicado a una distancia de 25 Km, de la capital de San Salvador. El Parque Recreativo tiene un área de 82 manzanas, contando con un potencial natural relevante ya que se ubica sobre un manto de lava o roca volcánica que sirve como recarga acuífera originando numerosas vertientes de agua cristalina que han permitido el desarrollo de vegetación que sólo en esta parte del país se puede apreciar, además de diferentes especies de plantas insectívoras que existen en el lugar.')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Turicentro Apulo',                 'Ilopango',             'San Salvador', 'El turicentro Apulo se encuentra ubicado a 16 kilómetros de la ciudad capital, San Salvador, esta cercanía lo convierte en un lugar bastante visitado por muchos turistas. Apulo significa en náhuatl: Lugar que se hunde en el agua. Este sitio se encuentra ubicado en el Cantón Dolores Apulo, municipio de Ilopango en el departamento de San Salvador. Contiguo al turicentro también se encuentra el lago de Ilopango de 72 Km.2, está entre los departamentos de San Salvador, Cuscatlán y La Paz. En esta zona la flora se clasifica como selva baja caducifolia, ya que los especímenes existentes son típicos de esa formación vegetal. El lago de Ilopango es de origen volcánico su cráter se ubica justamente al fondo del lago.')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Amapulapa',                        'Apastepeque',          'San Vicente',  'A 60 kilómetros de San Salvador se ubica Amapulapa, cuyo nombre en náhuatl significa: \"Río donde se hunden los Amates\", ubicado cerca de la ciudad de San Vicente a 60 kilómetros al oriente de San Salvador y con una extensión de 33 manzanas de terreno. La riqueza de este parque natural se encuentra en su suelo de origen volcánico dominado por cenizas y lava en el que afloran muchos nacimientos de agua de los cuales se nutre el mismo, la flora está caracterizada por los Amates hermosos y gigantes que brindan un espeso follaje y los cuales embellecen el lugar')");
        BaseDeDatos.execSQL("INSERT INTO balnearios (nombre,municipio,departamento,descripcion)VALUES('Termales de Santa Teresa',         'Concepcion de Ataco',  'Ahuachapan',   'Compuesta por 5 piscinas termales bien sean minerales o sulfuradas y cuyas temperaturas oscilan entre los 35 y 39 grados, lo cual sin duda alguna ofrece las condiciones necesarias cuando de relajación de músculos se trata, en la región de Ahuachapán se encuentra ubicado el atractivo turístico Termales de Santa Teresa. El secreto de la calidez de sus aguas viene dado por los denominados Ausoles, que no son sino formaciones geológicas típicas de zonas adyacentes a áreas volcánicas. Dada la naturaleza de dichas aguas a las mismas les han sido atribuidas propiedades curativas capaces de amainar el estrés, así como enfermedades asociadas o bien a la piel o bien a las articulaciones tales como la artritis, entre otras.')");

        //INSERCION DE LAGOS Y LAGUNAS
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna El Bijahua',       'San Francisco Menéndez',       'Ahuachapan',   'Los afluentes que recibe el CAC son los ríos La Palma y el río Cara Sucia, es ahora una pequeña loma que separa el cuerpo de agua en dos pequeñas lagunas; es por esta razón que los habitantes de la zona las identifican como dos lagunas: El Tular, que realmente es un pantano de poca profundidad, cubierta casi en su totalidad de plantas de tule (Typha angustifolia). A la segunda se le llaman Gamboa o El Bijahual,  la cual si posee espejo de agua; y habitan, y se reproducen caimanes.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('El lago de Ilopango',     'Ilopango',                     'Salvador',     'es un lago de origen volcánico en El Salvador. Mide 8 x 11 km, tiene una superficie de 72 km² y una profundidad de 230 m.1 Se sitúa a una altitud de 440 msnm a 16 km de la ciudad San Salvador, entre los departamentos de San Salvador, Cuscatlán y La Paz. Es el lago natural más grande de El Salvador. Sus aguas, con abundante pesca de mojarras, guapotes y juilines, es propio para la navegación a vela o en embarcaciones de motor')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('El lago Coatepeque',      'El Congo',                     'Santa Ana',    'lago de origen volcánico, situado a 18 km al sur de la ciudad de Santa Ana en el municipio de El Congo. Tiene una altitud de 745 msnm y una superficie de 25.3 km². Además, su profundidad es de 115 m.1 Cuenta con una isla llamada la Isla del Cerro o Teopán. El topónimo Coatepeque significa Cerro de Culebras en lenguaje náhuatl.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('El lago de Güija',           'Metapan',                      'Santa Ana',    'es un lago de América Central cuya superficie es compartida por El Salvador y Guatemala. Está ubicado en la frontera noroeste de El Salvador y el este de Guatemala, entre el departamento salvadoreño de Santa Ana y el departamento guatemalteco de Jutiapa, a una altura de 430 m s. n. m. (metros sobre el nivel del mar). El lago tiene una extensión aproximada de 45 km² (kilómetros cuadrados) y es compartida por ambos países El Salvador cuenta con el 74 % de su extensión y Guatemala con el otro 26 %')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna de Apastepeque',   'Apastepeque',                  'San Vicente',  'se ubica en el oriental departamento de San Vicente, la cual es una laguna que se formó en un cráter volcánico. Este lugar turístico ofrece dos ambientes para los visitantes: El rústico y «autóctono» (sin más comodidades que las que nos da la naturaleza). Allí la gente puede preparar alimentos a la intemperie, como en los viejos tiempos u optar por comprar un almuerzo listo para degustar en los restaurantes cercanos.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna de Alegría',       'Alegria',                      'Usulutan',     'Es de origen volcánico y se encuentra asentada sobre el volcán Tecapa, en los Cantones de San Juan y Apastepeque, ambos pertenecientes al Municipio de Alegría, Departamento de Usulután Dicho ecosistema se aloja bajo una depresión de aproximadamente 80 a 90m de profundidad, bordeada por tierras cultivadas de café y cubiertas por bosques húmedos caducifolios. Tres leyendas rodean el encanto de la laguna de Alegría. La primera se refiere a una sirena. Según la tradición oral, esta primera leyenda habla de una sirena que habita en las profundidades de la laguna. Se dice que aparece por las noches, encantando a los hombres jóvenes y de atractivo aspecto físico que se atreven a nadar en las aguas azufradas de la laguna de Alegría')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('La Laguna de Metapán',    'Metapan',                      'Santa Ana',    'se encuentra situada al noreste del Lago de Güija. Posee una extensión de 16 km² en época lluviosa y de 14 km² en época seca; su profundidad promedio durante las lluvias es de 6 m, pero en verano baja a unos 2 m. Está conformada por dos espejos de agua: el primero, situado junto al Bosque La Barra, tiene una superficie de 10 km cuadrados; el segundo, una superficie de 6 km², y se caracteriza por una isla ubicada en el centro, que es conocida popularmente como La Peñita. Posee playones anegadizos en el sector de Los Pajaritos, así como campos de cultivo.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna Ciega',            'Apastepeque',                  'San Vicente',  'Perteneciente a San Vicente, es un lago intermitente en El Salvador y tiene una altitud de 506 metros. Laguna Ciega está situada al sureste de Laguna de Apastepeque, y al sur de Cerro Agua Helada')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna La Bruja',         'Apastepeque',                  'San Vicente',  'Esta laguna es de origen volcánico y se ubica en el Cantón Calderas, Municipio de Apastepeque, y el Cantón San Esteban Catarina del Municipio San Esteban Catarina, Departamento de San Vicente.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna de Chanmico',      'San Juan Opico',               'La Libertad',  'Espejo de Agua. Chanmico en lengua Nahuat significa \"Lugar de Muertos\" y según cuenta la historia este fue un cementerio en tiempos precolombinos, luego se convirtió en laguna. La laguna está ubicada al Noroeste del Volcán de San Salvador en el cantón Chanmico Municipio de San Juan Opico, en el Departamento de La Libertad, y las coordenadas en que el equipo de trabajo la georeferenció fueron: 13º49´39” Latitud Norte y 89º20´30” Longitud Oeste')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna Verde',            'Ahuachapan, Apaneca y Juayú',  'Ahuachapan',   'La laguna está situada entre los cantones Suntecumal, Palo Verde y San Juan de Dios, municipios de Ahuachapán, Apaneca y Juayúa, entre los Departamentos de Ahuachapán y Sonsonate (MARN, 2000). El equipo de trabajo georeferenció la laguna entre las coordenadas: 13° 53’ 21.4” Latitud Norte y 89° 47’ 18.6” Longitud Oeste.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('La Laguna El Jocotal',    'El Transito',                  'San Miguel',   'Está ubicada en el municipio de El Tránsito, departamento de San Miguel, su altitud es de 24 m s.n.m., su extensión es de aproximadamente 500 manzanas. Ha recibido diferentes distinciones por la riqueza de su biodiversidad: en 1976 como área natural protegida.')");
        BaseDeDatos.execSQL("INSERT INTO lagos (nombre,municipio,departamento,descripcion)VALUES('Laguna de Aramuaca',      'San Miguel',                   'San Miguel',   'Está situada en los Cantones Miraflores y Cerro Bonito, a 9.7 Km. al sudeste de la ciudad de San Miguel, dentro del Departamento del mismo nombre, en la zona oriental de El Salvador. Por sus dimensiones de acuerdo con el Glosario de la Metodología del Inventario PREPAC (2004), se le clasifica como una laguneta. coordenadas: 13° 26’ Latitud Norte y 88°6’ Longitud Oeste; al noreste del río Grande de San Miguel y a una alitud de 85')");

        //INSERCION DE RUTAS
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta Azul',                       'Suchitoto, Quinquera, San Ignacio La Palma',                                   'San Vicente',              'La ruta azul es un trayecto turístico de El Salvador; que se comprende de los principales pueblos de la cultura tradicional salvadoreña. Una ruta pintoresca, que nutrirá tu viaje de experiencias en base a la historia precolombina, gastronomía tradicional y te brindará también una mirada hacia el pasado colonial.')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta Arqueologica',               'Zapotitan, San Juan Opico, Chalchuapa',                                        'Santa Ana, La Libertad ',  'La ruta Arqueológica está conformado por diferentes asentamientos Pipiles y de culturas precolombinas ubicados en el departamento de Santa Ana. Es un trayecto hacia los días de nuestros ancestros, un viaje con destino al origen de nuestros tiempos. Los destinos arqueológicos son: Joya de Ceren, Ruinas del Tazumal,Casa Blanca, Ruinas de San Andres')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta del Paraiso Artesanal',      'Suchitoto, Tejutla, San Ignacio, Citala',                                      'Chalatenango, Cuscatlan',  'En la ruta paraíso artesanal encontraras la cuna de las artesanías de El Salvador, gozarás de un recorrido lleno de color, folklore y la acogedora hospitalidad de los lugareños. En cuanto a gastronomía, también puedes encontrar platillos típicos propios de la zona; además de las ya conocidas pupusas, entre otros manjares, esta ruta se compone de seis pueblos: Cihuatán, Colima, La Palma, San Ignacio, Miramundo, Citalá')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta de las Flores',              'Ahuachapan, Concepcion de Ataco, Apaneca, Juayua, Salcoatitan y Nahuizalco',   'Ahuachapan, Sonsonate',    'Muy probablemente esta es una de las rutas turísticas más largas de El Salvador, además de ser la más famosa ya que en su trayecto podrás encontrar atractivos del departamento de Ahuachapán, como bosques,un clima fresco y estructuras que datan de la época colonial, como la Iglesia Nuestra Señora de la Asunción, el Centro Histórico de la ciudad; además de los “obsequios” de la naturaleza, como los Ausoles, que son emanaciones de vapor que surgen de las entrañas de la tierra.  ')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta de la Paz',                  'Incluye a los 26 municipios',                                                  'Morazan',                  'Esta ruta se ubica en el departamento de Morazán, y se compone de once pueblos. Se le conoce como «Ruta de La Paz» debido a que ha gozado de un largo período de tranquilidad desde el final del conflicto armado en El Salvador. Cuenta con 11 pueblos pintorescos y llenos de vida, pero alejados del bullicio de las urbes de las cabeceras departamentales, lo que brinda una sensación constante de calma y serenidad. Este trayecto se caracteriza por las vistas que podrás apreciar mientras te desplazas por las carreteras sobre las montañas.')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta las Mil Cumbres',            'Multiples municipios',                                                         'Usulutan','La ruta de las mil cumbres de trata de un recorrido que se da en El Salvador Este tiene como inicio las costas de este país para terminar en las alturas del departamento de Usulután. Dentro de lo que ofrece este paseo, será posible ubicar tanto hermosas playas como impresionantes reservas naturales. ')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta Fresca',                     'La Palma, San Ignacio, Cítala, La Reina',                                      'Chalatenango',             'Se le conoce como Ruta fresca al trayecto que atraviesa un conglomerado de pueblos cuyo clima es considerado cálido/fresco. Tal como se describe, este viaje atraviesa praderas y campos entre montañas, con paradas en pueblos pequeños rurales; en el camino notarás que el paisaje se compone por lo general de granjas, pastizales con un horizonte de pinos y neblina que toca las montañas')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Ruta Monseñor Romero',            'San Salvador, Santa Tecla, Antiguo Cuscatlán',                                 'San Salvador',             'Si eres seguidor del a fe católica, esta ruta puede ser de tu interés ya que, este trayecto se basa en la vida del arzobispo Óscar Arnulfo Romero. Es un camino por la memoria del mártir, donde podrás conocer más sobre su historia, enseñanza y sus aportes a la religión. Los destinos que comprenden esta ruta son: Centro Moseñor Romero y Museo de los Mártires de la Universad Centroamericana José Simeón Cañas (UCA). Catedral Metropolitana. Museo de La Palabra y la imagen (MUPI). Centro Histórico Moseñor Romero: Hospital Divina Providencia. Museo Nacional de Antropología. Santuario Monseñor Romero de las Hermanas Chacón')");
        BaseDeDatos.execSQL("INSERT INTO rutas (nombre,municipio,departamento,descripcion)VALUES('Corredor Arqueológico Subacuático','Acajutla',                                                                    'Sonsonate',                'El corredor arqueológico subacuático contempla cinco sitios con vocación para el buceo y donde se puede apreciar barcos naufragados y sus arrecifes de coral, estos son: SS Douglas, ubicado a 2.26 km hacia el suroeste de la playa Punta Remedios, en Acajutla, Sonsonate; Cheribon, en la playa Los Cóbanos, Sonsonate')");

        //INSERCION DE CATEDRALES
        BaseDeDatos.execSQL("INSERT INTO catedrales (nombre,municipio,departamento,descripcion)VALUES('Iglesia El Rosario',                         'San Salvador',         'San Salvador', 'Desde 1971, la iglesia El Rosario es un patrimonio religioso de los salvadoreños como una de las últimas iglesias construidas en la capital, que conserva un diseño arquitectónico moderno, enriquecido con influencia europea y única a nivel del continente. Ubicada frente al parque Libertad es una edificación que mide 24 metros de ancho y 80 de largo cuya forma es oval sin columnas, con 22 metros de altura. En comparación a otros templos, la iglesia no tiene pilares que obstaculicen la visibilidad de los fieles hacia el altar y las vistosas imágenes religiosas que destacan en su interior. Todo visitante apreciará sus singulares paredes de concreto visto, arqueadas por numerosos vitrales que colorean el interior sombrío del templo, elementos visuales que le dan una riqueza increíble a los atardeceres capitalinos. Su forma es más la de un hangar de aviones que la de una iglesia tradicional ')");
        BaseDeDatos.execSQL("INSERT INTO catedrales (nombre,municipio,departamento,descripcion)VALUES('Catedral de Santa Ana',                      'Ciudad de Santa Ana',  'Santa Ana',    'La Catedral de la Señora Santa Ana, es la iglesia principal de la diócesis católica de Santa Ana, en la ciudad de Santa Ana, El Salvador. Este templo tiene la advocación de la Señora Santa Ana, la madre de la Bienaventurada Virgen María. El lugar donde hoy está la catedral de Santa Ana se encontraba la parroquia central, la cual fue construida entre 1575 y 1576, siendo semidestruida por un rayo en el siglo XIX. Cuando se creó la Diócesis de Santa Ana se iniciaron los preparativos para reconstruir la parroquia central de la ciudad; esta reconstrucción se autorizó en 1904 y comenzó el 21 de enero de 1906. Fue consagrada el 11 de febrero de 1913. La construcción, sin embargo, continuó en las décadas que siguieron hasta que finalmente fueron terminadas el 24 de febrero de 1959, cuando el altar de mármol de la imagen de la Señora Santa Ana fue consagrada y terminada. En 1993 se inició la restauración de la catedral; el 22 de abril de 1995 fue declarada Monumento Nacional. ')");
        BaseDeDatos.execSQL("INSERT INTO catedrales (nombre,municipio,departamento,descripcion)VALUES('Catedral Metropolitana de San Salvador',     'San Salvador',         'San Salvador', 'La Catedral Metropolitana del Divino Salvador del Mundo es la iglesia principal de la arquidiócesis católica de San Salvador, en El Salvador, y sede del arzobispo metropolitano. En 1888 se terminó una catedral de madera que sirvió como asiento de los arzobispos de San Salvador, en el solar que antes ocupó la iglesia de Santo Domingo. El 8 de agosto de 1951, este templo fue consumido por un incendio. Desde 1951 hasta, quedó vacío el solar de la catedral sin haberse empezado construcción alguna. En 1953 se llevó a cabo un concurso para elaborar un diseño para una nueva catedral, pero este concurso fue declarado desierto en el 9 de mayo del mismo año. Después se solicitar un diseño a Europa. En el 11 de marzo de 1954, el arzobispado informó que los planos elaborados por el arquitecto Dominikus Böhm habían llegado de Alemania. En 1956, el arzobispo Luis Chávez y González emprendió las obras de reconstrucción, se colocó la primera piedra en el viernes 12 de octubre. de la catedral que se prolongaron por cuatro décadas. ')");
        BaseDeDatos.execSQL("INSERT INTO catedrales (nombre,municipio,departamento,descripcion)VALUES('La Parroquia Nuestra Señora de la Merced',   'San Salvador',         'San Salvador', 'Ubicada en el Centro histórico de San Salvador, un legado de obras de arte, historia, devoción, tradiciones y fe. Una pequeña iglesia importante para toda Centro América por el repicar de sus campanas, ella guarda el recuerdo histórico de aquel 5 de noviembre de 1811 cuando se dio el primer grito de independencia y del glorioso 15 de septiembre de 1821, cuando El Salvador y las otras naciones centroamericanas se declararon naciones libres y soberanas, cuando era párroco el Pbro. Y Dr. José Matías Delgado. Este fue el lugar donde en el año 1525 nació San Salvador. Actualmente no posee su diseño original, del templo colonial no queda más que el Campanario que todavía puede admirarse en pie con sus cuatro campanas, y las bellas imágenes que son uno de sus tesoros más valiosos en tradición, devoción y fe. ')");
        BaseDeDatos.execSQL("INSERT INTO catedrales (nombre,municipio,departamento,descripcion)VALUES('Catedral basílica Reina de la Paz',          'Ciudad de San Miguel', 'San Miguel',   'La Catedral Basílica Santuario Nuestra Señora de la Paz, más conocida como Catedral de San Miguel, se encuentra ubicada en la ciudad de San Miguel, El Salvador. Se dice que el principal material utilizado para la construcción de la catedral fue la piedra volcánica transportada desde el volcán de San Miguel que es popularmente conocida como «curruncha». La catedral puede albergar en su interior hasta dos mil personas, por lo que se considera la segunda con mayor capacidad en el país después de la Catedral Metropolitana de San Salvador; así como la construcción más alta de la zona oriental de El Salvador con una altura de 25 metros desde el suelo hasta el techo ')");

        //INSERCION DE Sitios Arqueologicos
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Joya de Cerén',                    'San Juan Opico',   'La Libertad',  'Joya de Cerén es el único espacio en el país donde se conservan evidencias de la vida cotidiana de los pueblos mayas que residieron en la zona hace más de 1600 años. Esta ciudad fue cubierta por las cenizas producidas en una erupción del volcán de Ilopango en el siglo VII d.C. Lo sorprendente es que los arqueólogos expertos aseguran que los aldeanos lograron huir a tiempo ya que no se han encontrado restos de cuerpos humanos. En los recorridos marcados por las estructuras descubiertas apreciará la cotidianidad de un pueblo maya agricultor que se vio obligado a abandonar sus hogares a causa de una fuerte erupción volcánica en el año 250 y nuevamente fue habitado en el año 400 rindiendo tributo a los gobernadores que habitaron el Sitio San Andrés, a tan solo 3 kilómetros de distancia. El recorrido está compuesto por tres áreas de excavación donde visualizará diez estructuras separadas. En ellas verá algunos dormitorios, área de cocina donde se hallaron vasijas con restos de comida, platos de barro; también bodegas y terrenos de cultivos limitados con cercos de madera. ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Casa Blanca',                      'Chalchuapa',       'Santa Ana',    'Su antigüedad se remonta a más de cinco mil años, ya que sus estructuras piramidales narran una historia ancestral de los períodos preclásico, clásico y posclásico. Casa Blanca tiene un área de 6 hectáreas, la cual representa un fragmento de un sitio mucho mayor, ahora en gran parte destruido debido al crecimiento de la ciudad de Chalchuapa. Hay un museo donde puede contemplar algo único que no se encuentra en otra parte del país: una estela con escritura maya. Además, el lugar te ofrece un taller de añil, donde puedes aprender los distintos métodos de producción relacionados a este tradicional colorante natural y así vivir una de las experiencias culturales más significativas en El Salvador ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('San Andrés',                       'San Juan Opico',   'La Libertad',  'En esta antigua ciudad maya, residían todo tipo de personas, como sacerdotes, gobernantes, comerciantes y artesanos. Ahí se puede apreciar bastantes plazas con formas de pirámides y algunas casas. Este sitio era centro tanto ceremonial como regional. Es uno de los lugares más importantes de El Salvador por la historia prehispánica que posee. San Andrés es un sitio arqueológico que se encuentra en el valle de Zapotitán, a solo cinco kilómetros de Joya de Cerén, en el departamento de La Libertad. El sitio comprende una acrópolis, que es un espacio arquitectónico en el que se realizaban actividades restringidas a un grupo especial de personas, posiblemente dirigidas por la élite gobernante. ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Ruinas del Tazumal',               'Chalchuapa',       'Santa Ana',    'Situado en el corazón del municipio de Chalchuapa, en el departamento de Santa Ana, a tan solo 80 kilómetros de la ciudad capital de San Salvador. Tazumal es un sitio singular que destaca las huellas de la civilización indígena que dominó nuestro país antes de la era colonial, su significado “lugar donde se consumen almas” en lengua nahua-quiché. Su primera referencia data del año 1892, registrado formalmente en 1940 por Stanley Boggs, quien tuvo la oportunidad de identificar 13 estructuras. ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Cihuatan',                         'Aguilares',        'San Salvador', 'La ciudad de Cihuatán es uno de los tesoros arqueológicos más espectaculares e importantes de Centroamérica. Comprende un estimado de 300 hectáreas de construcciones continuas, incluyendo un núcleo de grandes estructuras cívico-religiosas, rodeadas por un compacto complejo de arquitectura doméstica. Cihuatán fue ocupado sólo por un corto tiempo, entre 900 d.C y 1100 d.C., y abandonado durante la fase denominada Guazapa. ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Ciudad Vieja',                     'Suchitoto',        'San Salvador', 'Ciudad Vieja es el nombre por el que actualmente es conocida una desaparecida población española de la otrora Alcaldía Mayor de San Salvador, una antigua división político-administrativa de la Corona Española durante la colonización de América, la cual formaba parte del relativamente extenso Reino de Guatemala (no confundir con la república guatemalteca). Más del 80 % de lo que hoy conforma El Salvador, incluyendo algunos territorios que hoy forman parte de Honduras, constituían dicha alcaldía mayor. Ciudad Vieja se trata nada más ni menos que de la primigenia San Salvador durante su refundación en 1528 (la ciudad había sido fundada ya tres años antes, en 1525, pero fue abandonada presuntamente por la resistencia de los naturales del territorio del Señorío de Cuzcatlán). La localidad fue fundada con el título de Villa y el nombre de San Salvador, con el objetivo que sirviera como una ciudad de españoles en el territorio para \"pacificar\" a los pobladores, conquistarlos, dominarlos, cristianizarlos y castellanizarlos. ')");
        BaseDeDatos.execSQL("INSERT INTO sitios_arqueologicos (nombre,municipio,departamento,descripcion)VALUES('Santa Leticia',                    'Apaneca',          'Ahuachapan',   'El sitio Arqueológico de Santa Leticia se ubica a 1400 metros sobre el nivel del mar en Apaneca, departamento de Ahuachapán. Es una zona que fue habitada por los mayas y comprende 15 hectáreas de terreno. Está constituida por una serie de figuras o esculturas muy representativas llamadas \"gordinflones\" o \"barrigones\" de diferentes pesos y medidas. Comprende también restos de una pirámide, montículos y terraza artificial. Esta importante población de Santa Leticia tuvo un desarrollo cultural muy notable, sobre todo por sus relaciones con los pueblos Chalchuapa y Atiquizaya. ')");

        //INSERCION DE Sitios Volcanes
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de Santa Ana',      'Ciudad de Santa Ana',  'Santa Ana',    'El volcán de Santa Ana también es conocido como Volcán Ilamatepeq. Este volcán se ubica en el departamento de Santa Ana y se tienen registros de sus últimas erupciones que ocurrieron en los años 1904, 1920 y la última que fue en 2005. Está ubicado a una altura de 2,382 metros sobre el nivel del mar por lo que también es considerado como uno de los lugares más altos de El Salvador. El llamatepec se ubica en la cordillera de Apaneca, dentro de un bosque nuboso montañoso tropical, sobre una región mayormente cafetalera a unos 65 kilómetros al oeste de San Salvador. Las principales actividades económicas de la región son la agricultura y el turismo. Su última erupción ocurrió el 1 de octubre de 2005, fue una explosión de cenizas y rocas volcánicas y una corriente de agua caliente bajó desde el cráter, provocando la muerte de dos personas y forzó a la evacuación de los habitantes de la zona de San Blas. ')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de Izalco',         'Izalco',               'Sonsonate',    'El volcán de Izalco es considerado como el más joven de los volcanes de El Salvador y uno de los más jóvenes del continente Americano. Su origen se dio en el año de 1770, cuando un agujero en las faldas del Volcán de Santa Ana comenzó a emanar humo y cenizas. Durante 196 años el volcán hizo erupción permanentemente, y dichas erupciones eran vistas hasta el océano, razón por la cual obtuvo el sobrenombre de Faro del Pacífico. Su actividad hizo que se formara un cono de 650 metros, con un cráter de 250 metros de diámetro.')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de San Salvador',   'Quezaltepeque',        'La Libertad',  'El volcán de San Salvador también es conocido como volcán de Quezaltepeque. Está ubicado entre los municipios de Quezaltepeque, San Juan Opico, Colón, Nejapa y Nueva San Salvador en el departamento de La Libertad. Se encuentra a una distancia de once kilómetros de la ciudad de San Salvador. Las primeras erupciones del volcán de San Salvador fueron al final de la período terciario y principios del Cuaternario. La última erupción registrada del volcán de San Salvador fue el 7 de junio de 1917; esta erupción provocó que se extinguiera un lago que había en el cráter del volcán y en su lugar quedó una elevación, la cual es conocida como El Boquerón. ')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de San Miguel',     'Ciudad de San Miguel', 'San Miguel',   'El volcán de San Miguel es mejor conocido como Volcán Chaparrastique (que significa «tierra calurosa del chaparro o tierra del calor»), se encuentra ubicado en el municipio de San Miguel, específicamente a once kilómetros de la ciudad de San Miguel. Se encuentra en la cordillera de Chinameca. Es el tercer volcán más alto del país, su cráter central tiene unos 800 metros de diámetro y varios agujeros por los cuales ha expulsado lava quemada. Su cono volcánico está considera como uno de los mejor formados de Centro América. El volcán Chaparrastique está considerado como uno de los seis volcanes más activos de El Salvador. En los últimos 300 años ha tenido más de 26 erupciones. La última erupción del volcán había sido en el año de 1976, sin embargo, el 29 de diciembre de 2013 se produjo una erupción de ceniza volcánica que hizo evacuar a los pobladores de las zonas cercanas sin reportar víctimas. ')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de San Vicente',    'Guadalupe',            'San Vicente',  'El volcán de San Vicente es conocido también como Volcán Chinchontepeq, se ubica entre los municipios de Guadalupe y Tepetitán en el departamento de San Vicente; y San Juan Nonualco y Zacatecoluca en el departamento de La Paz; a 60 kilómetros al este de San Salvador. Este es considera como el segundo volcán más alto de El Salvador. El volcán de San Vicente posee dos elevaciones: La más alta tiene 2,173 msnm. con un pequeño agujero en medio de lo que un día fue un cráter; la otra elevación se encuentra más baja, a 2,083 msnm, posee forma de cono de cráter abierto hacia el este. Al lado sur y en la base del volcán de San Vicente se encuentran manantiales de aguas termales los cuales son comúnmente conocidos como infiernillos, éstos manantiales emanan vapores fuertes y humo sulfúrico. Al norte del volcán se encuentra el Valle de Jiboa, una de las zonas más ricas de cultivo en El Salvador. Hasta la fecha no se conoce ninguna erupción del volcán de San Vicente')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán de Conchagua',      'Conchagua',            'La Unión',     'El volcán de Conchagua (su nombre es de origen Lenca y significa \"Valle estrecho\") se encuentra ubicado a 4.6 km al sureste del municipio de Conchagua en el departamento de La Unión, pose una altura de 1,243 metros sobre el nivel del mar. El volcán está cubierto de vegetación en la actualidad. En el volcán de Conchagua se encuentra un parque ecológico desde el cual pueden observarse algunas islas del Golfo de Fonseca como Meanguera, Meanguerita y Amapala ')");
        BaseDeDatos.execSQL("INSERT INTO volcanes (nombre,municipio,departamento,descripcion)VALUES('Volcán Tecapa',            'Alegría',              'Usulután',     'El volcán Tecapa (significa «Laguna de piedras») se encuentra a 2 kilómetros al sur del pueblo de Alegría en Usulután. Al centro del volcán existe una laguna con aguas de color turquesa debido a que reposa sobre mantos de azufre. La parte del cráter mide unos 900 metros y la laguna 350 metros. Ésta es conocida como la Laguna de Alegría y es uno de los atractivos turísticos de el Salvador. La Laguna de Alegría también es conocida como La Esmeralda de América. En el volcán Tecapa se observan fumarolas y fuentes termales, dejando en claro que existe una actividad volcánica en el lugar. No se tienen registros de erupciones de este volcán. ')");

        //INSERCION DE Sitios Montañas
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('El Pital',                         'San Ignacio',  'Chalatenango', 'Es una montaña ubicada en el punto más alto de El Salvador, a 2,730 metros sobre el nivel del mar, en el departamento de Chalatenango. Además del incomparable clima fresco que ofrece gracias a su altura, posee vistas paisajísticas de la ciudad de San Salvador, del volcán de Izalco y de algunas partes de Honduras.')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('Montecristo',                      'Metapán',      'Santa Ana',    'Un Parque Nacional, ubicado en el departamento de Santa Ana que está compuesto por el viejo cerro, el cerro Miramundo y el cerro Brujo. En este lugar se combinan armónicamente la aventura, el fresco clima, la variedad de flora y fauna, y el senderismo.')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('El Boquerón',                      'Nejapa',       'San Salvador', 'Un paisaje natural sorprende, situado en el cráter del volcán de San Salvador a 11 kilómetros de la capital y a 20 minutos de Santa Tecla. El cráter tiene 1.6 kilómetros de diámetro y 558 metros de profundidad. El parque El Boquerón cuenta con senderos que permiten apreciar el esplendor de la flora y fauna del lugar.  Entre las especies de flora destacan cipreses, geranios, cartuchos, hortensias, antorchas, begonias y sultanas silvestres, además de las fresas y cerezas que los lugareños comercializan. De la misma manera, en la fauna se encuentran armadillos, mapaches, venados, zorros, entre otras. En el camino se ubican numerosos miradores y restaurantes con extraordinarias vistas hacia San Salvador, en los que se puede degustar de todo tipo de gastronomía típica salvadoreña.')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('Parque Nacional Los Volcanes',     'San Salvador', 'San Salvador', 'Está compuesto por las cumbres del volcán de Izalco, Santa Ana y el Cerro Verde. La riqueza de este sitio radica en los habitantes con herencia étnica y estructuras coloniales combinadas con la naturaleza y aventura. Cuenta con senderos, miradores, cafeterías, ventas de artesanías, guías locales y un hotel de montaña que se rumora que está pronto a reabrirse. Por razones de seguridad, las caminatas a las cumbres de los volcanes de Izalco y Santa Ana deben hacerse en compañía de guías locales y personal especializado de la zona. ')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('El Cerro Borroñoso',               'Yamabal',      'Morazán',      'Es una montaña en El Salvador. El cerro está en el Departamento de Morazán en la parte oriental del país, a 110 km al este de la capital, San Salvador. La altitud del cerro es de 1127 metros sobre el nivel del mar, y 101 metros sobre el terreno circundante. El ancho de la base es de 1.3 kilómetros. El Cerro Borroñoso está en el área del Volcán Cacahuatique en la Unidad morfo-estructural de la Gran Depresión Central. Está en la sub-cuenca El Corozal de la cuenca del Río Grande de San Miguel.1 El terreno alrededor del Cerro Borroñoso es principalmente compuesto de colinas y al norte de montañas. El punto más alto alrededor es de 1645 sobre el nivel del mar, 4.3 km al norte del cerro. El área alrededor es muy populosa, con 75 personas por kilómetro cuadrado. La ciudad principal más cercana es San Francisco Gotera, a 11.1 km al este del Cerro Borroñoso. ')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('El cerro San Jacinto',             'San Jacinto',  'San Salvador', 'Está ubicado en las demarcaciones de los municipios de San Marcos, San Salvador, Santo Tomás y Soyapango en el departamento de San Salvador, El Salvador. Sobre su cima funcionó el Teleférico San Jacinto hasta el año de su cierre en 2001. Tiene una elevación de 1.153 msnm.')");
        BaseDeDatos.execSQL("INSERT INTO montanias (nombre,municipio,departamento,descripcion)VALUES('El Cerro Verde o Cuntetepeque',    'El Porvenir',  'Santa Ana',    'Es un volcán extinto ubicado en el Departamento de Santa Ana, El Salvador, en la cordillera de Apaneca. Tiene una altura de 2030 msnm y su cráter se encuentra erosionado y cubierto por un espeso bosque nebuloso. Se estima que su última erupción fue hace 25 mil años a. C. El Cerro Verde es parte del Parque Nacional Los Volcanes El Salvador contando con una extensión de 2,734.6 hectáreas y una total de todo el parque de 4,500 hectáreas, entre tierras estatales, municipales y privadas que es administrado por el Ministerio de Medio Ambiente y Recursos Naturales; ofrece miradores a los volcanes de Santa Ana, Izalco y al Lago de Coatepeque, además de un orquideario, paseo por el bosque y escaladas al mismo Volcán de Izalco (altura 1,980 metros sobre el nivel del mar) y al de Santa Ana (altura 2,381 metros sobre el nivel del mar). El parque también cuenta con tres senderos recreativos: Las Flores Misteriosas, Ventana a la Naturaleza y Antiguo Hotel de Montaña. ')");

        //INSERCION DE Sitios Miradores
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('Mirador de La Giralda',               'Comasagua',    'La Libertad',  'Un clima fresco, un ambiente agradable y el mejor panorama es lo que se podrá observar en el mirador de La Giralda. Está ubicado dentro de la conocida Ruta del Café de Comasagua, específicamente en el departamento de La Libertad, y no solo se podrá disfrutar de unas hermosas vistas, sino también de servicios de primer nivel. La vista se pierde en el horizonte, pero es posible detallar la estructura del volcán de San Salvador y el cerro de Montecristo. Lo más destacable de esta experiencia única, es el aroma que se percibe en todo el espacio ')");
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('Mirador de los Planes de Renderos',   'Panchimalco',  'San Salvador', 'Es un mirador espectacular y, lo mejor, es que está en plena vía pública, por lo que no hará falta pagar nada de dinero. Si se dispone de un coche y se puede visitar de noche, lo que se puede ver, valdrá totalmente la pena, porque es una de las mejores actividades que se pueden realizar en este país. El mirador se encuentra en San Salvador, en la zona conocida como Panchimalco, por lo que no habrá que pasar mucho tiempo de viaje para llegar hasta allí. Existen otras actividades que se pueden realizar en sus inmediaciones para disfrutar aún más, como visitar los parques de Balboa y el parque de la Familia ')");
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('Mirador de las Cien Gradas',          'Alegría',      'Usulután',     'Este es uno de los lugares turísticos más reconocidos y visitados por las personas que llegan a El Salvador para recorrerlo. Ofrece la opción para observar unas vistas panorámicas que se levantan sobre una laguna de azufre que se puede visitar y hasta bañarse en ella, si es el deseo. Eso sí, el olor en todo el espacio es penetrante, por el propio azufre, pero eso no quita las ventajas de participar de una visita. ')");
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('Mirador Paradise',                    'Berlín',       'Usulután',     'Este mirador, mejor conocido como el mirador de las Manos Gigantes, es un espacio increíble para tomarse una buena foto en la mano más grande de todo el país. También permite que se realice la visita guiada por los terrenos de café, disfrutando de un aroma exquisito, y llegar hasta una fuente de aguas cristalinas. Lo mejor es que es un mirador amplio, que ofrece la opción para observar una gran cantidad de espacios, casi en 360°. ')");
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('Mirador El Espíritu de la Montaña',   'Conchagua',    'La Unión',     'El mirador de El Espíritu de la Montaña, un espacio de ensueño y vida para respirar aire, disfrutar de la vista y pasar un tiempo de recreo y desconexión muy valorado. En este mirador se puede observar la perfecta fusión entre un ambiente de montaña, verde y frondoso, y las aguas que le acompañan justo al lado. Es una experiencia increíble que dejará a todos los que se acerquen impresionados de las vistas tan perfectas ')");
        BaseDeDatos.execSQL("INSERT INTO miradores (nombre,municipio,departamento,descripcion)VALUES('La puerta del Diablo',                'Panchimalco',  'San Salvador', 'Es el punto más alto de San Salvador, ubicado un kilómetro al sur del Parque Balboa, dentro de Los Planes de Renderos. Si se conduce en vehículo, podrá dirigirse por la señalización de la calle. Podrá estacionarse en el parqueo asignado, muchos lugareños ofrecen darle seguridad a su carro por $1.00. Los buses que frecuentan en la zona son: Ruta 12 microbús (con destino al Parque de la Familia y los Planes de Renderos). Podrá abordarlo en el Centro de San Salvador. Costo de pasaje ronda los $0.25 o $0.35 ')");
    }
}
